### ISSUE TITLE
Simple comparison plots

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#10]
Produce comparison plots between two questions
![A3_gender](https://user-images.githubusercontent.com/74262873/136376726-43bc15cc-fbee-4eda-8d24-3172ec47883a.png)

- [x] Make a function that produces the comparison plot between simple question types (single choice).

What should be adjustable:
- [x] Color Scheme (with a default value that can be set in a header file)
- [x] Displaying or hiding the question title
- [x] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [x] Option for with or without the total bar (see example first bar)
- [x] Option for adding spaces between certain bars (e.g. space between Total and the rest in the example figure)
- [x] Displaying the "No Answers" or hiding them
- [x] Threshold for percentage to be printed out

- [x] Expand it to entail more than 2 questions for comparison as e.g. here:
![B1_Financed_section_nationality](https://user-images.githubusercontent.com/74262873/136378450-ff2855f0-54c4-4b42-be1d-92a0993ee32d.png)

**Comment by Cheedge** [comment]
> Hi @Cheedge, thank you for the nice work!
> 
> 1. Figure dimensions = how broad the figure is compared to it's width. Usually it's controlled in matplotlib with figsize=(10,5) or similar.
> 2. Yes, in the example it's the total bar. But I would also like to be able to choose that e.g. the first 3 bars should have a space to the rest of the bars.
> 
> Some other comments:
> 
> * Try to make all bars at the same total height, not dependent on the numbers of answers per A...
> * Try to order the bars according to the answer order in the xml file (use Li's code for it)
> * Import title from the xml structure (use Li's code for it)
> * Import answer titles from the xml structure (use Li's code for it)
> 
> A more general comment:
> 
> * We should decide on the precision to be used for displaying percentage.

Hi @lheckmann ,
ok, let's see this,
multiple comparison case

![new_multi0](https://user-images.githubusercontent.com/61045942/137636358-fc13e0f6-87a9-4ae1-9883-8db6c9f4800a.png)

you can also change interval, name, tiltle...

![new_multi1](https://user-images.githubusercontent.com/61045942/137636397-0ac777a3-7ed9-40b2-911f-d9e5eec89bf8.png)

here is the single comparison case:

![new_only_graph0](https://user-images.githubusercontent.com/61045942/137636417-c142916e-bc4a-4aeb-8f5e-fd7ee16f04fa.png)


please check these,

1, first two are multiple comparison graph, and last one is single percentage comparison plot.

2, can show or hide title

3, we can set the figure size

4, with or without the total bar (see example first bar)

5, Option for adding spaces between certain bars (e.g. space between Total and the rest in the example figure)

6, Displaying the "No Answers" or hiding them

7, Threshold for percentage to be printed out, here I set to 5%

8, works for more than 2 questions for comparison, as show above

9, also defined a func to import title and names from previous read_xml code, also you can set it as you like as above or just not display it.

if there is no changes needed for the graphic part, I can make code clean, then pull the request.

Best
Q.Z.

**Comment by TheFlike** [comment]
s = LimeSurvey("SurveyFramework/data/survey_structure_2021.xml")
s.read_responses("SurveyFramework/data/dummy_data_2021_codeonly.csv")
s.output_folder = ''
s.theme["rc"]["figure.figsize"] = (16,9)
s.theme["palette"] = "Reds"
s.plot('A1', compare_with='A6', save=True, totalbar=True,
       threshold_percentage=10, bar_positions=[0,1.5,2.5], 
       answer_supress=['No Answer'], add_questions=['A6'], legend_columns=6,
       title = True)

should cause the following picture

![A1](https://user-images.githubusercontent.com/60603101/151785333-409a81ee-330e-48b5-b4cd-d2cc42ae51dd.png)

**Comment by TheFlike** [comment]
LIst of Examples from minimalistic to complex:
s = LimeSurvey("SurveyFramework/data/survey_structure_2021.xml")
s.read_responses("SurveyFramework/data/dummy_data_2021_codeonly.csv")
s.output_folder = ''
s.theme["rc"]["figure.figsize"] = (16,9)
s.theme["palette"] = "Reds"

s.plot('A1', save=True)
![A1](https://user-images.githubusercontent.com/60603101/151880708-b9bcfe27-d3c1-48b9-a270-6d7a55a99c3f.png)


s.plot('A1', compare_with='A6', save=True, plot_title=False)
![A1](https://user-images.githubusercontent.com/60603101/151880585-c5b1a898-6b16-41d2-a13e-0045fe3d585a.png)

s.plot('A1', compare_with='A6', save=True, totalbar=True,
       threshold_percentage=10, bar_positions=[0,1.5], 
       answer_supress=['No Answer'], add_questions=['A6'], legend_columns=6,
       plot_title = 'Putting in my own title')

![A1](https://user-images.githubusercontent.com/60603101/151880939-3676d2a7-525b-4149-975c-56b0b98ae705.png)

**Comment by lheckmann** [comment]
Looks very nice!
One more small detail: Can you order the bars in the order of the answer in the structure part of the survey object (as done for the simple single choice figure)?

**Comment by TheFlike** [comment]
Maybe I didn't have the easiest way, but this now should also work... in theory:
s.plot(
    "A1",
    compare_with="A6",
    save=True,
    totalbar=True,
    threshold_percentage=10,
    bar_positions=[0, 1.5, 2.5, 4.5],
    answer_supress=["No Answer"],
    add_questions=["A6"],
    legend_columns=6,
    plot_title="Putting in my own title",
)

should now plot:
![A1](https://user-images.githubusercontent.com/60603101/152770903-2ad082af-a5fd-4a34-805c-46e74d0e4158.png)

I will continue and add the combining of bars via tuples ('not sure',['I don't remember', 'No']) should then cause a bar 'not sure' which includes percentages of 'I don't remember' and 'No' e.g.
