### ISSUE TITLE
Desgin color schemes

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#101]
Design default color schemes for all organisations (Helmholtz, Leibniz, Max Planck, TUM, IPP) involved using their Logo's and organisation's colors.

**Comment by lheckmann** [comment]
Websites to look up Logo's and colors:
MPS: https://www.phdnet.mpg.de/home
Helmholtz: https://www.helmholtz.de/karriere/karriere-bei-helmholtz/promovierende/helmholtz-juniors/
Leibniz: https://leibniz-phd.net/
TUM: https://gc.gs.tum.de/
IPP: can be seen on the N2 website header here: https://www.phdnet.mpg.de/n2, color here can be similar to above, will not be used in comparisons

**Comment by Tianbe** [comment]
Question @lheckmann : Where / how should I put the colors in the code? I could for example create an aditional file "colors.py" in the plot folder and save the RGB/Hex values of the colors of the respective color schemes in a class ColorSchemes.

**Comment by lheckmann** [comment]
Yes, that sounds good!

**Comment by Tianbe** [comment]
How many colors should actually be in the color scheme? maybe 5?

**Comment by lheckmann** [comment]
You mean per color scheme?
I think there is an option with cmap or so that one can keep it flexible. So if the user chooses 3 it's 3 that have more contrast with each other, if it's 7 it's 7 but with less contrast since it is chosen from the same palette.

**Comment by Tianbe** [comment]
Ok, because currently I just defined some custom colors for each organization, but the idea would be to take those few colors as a basis for a colormap with an arbitrary number of colors, like in this example code https://matplotlib.org/stable/gallery/color/custom_cmap.html

**Comment by lheckmann** [comment]
Yes exactly!

**Comment by Tianbe** [comment]
That makes sense, I will implement it accordingly =)

**Comment by Tianbe** [comment]
I pushed my code on a new branch: https://github.com/N2-Survey/SurveyFramework/tree/101-desgin_color_schemes
You can simply run the main function to obtain some examples. the color schemes of helmholtz and tum are relatively similar, but I could not find different colors on their website. Maybe those themes need to be adjusted. Also a documentation of the class is still missing, but I first wanted to check if the outcome of the example-plots match your expectations @lheckmann.

**Comment by lheckmann** [comment]
What are the names of the color schemes?

And I just use them with `s.theme["palette"] = name` right?

**Comment by Tianbe** [comment]
@lheckmann sorry for the late reply. Currently the color schemes are saved as attributes of the `ColorSchemes` class. If you call `ColorSchemes(x)` you will obtain an instance of the `ColorSchemes` class and x is the number of colors in the respective colorschemes. `ColorSchemes(5).mps` for example give you an seaborn color palette with 5 colors (corresponding to the pallete of the MPS).
As you mentioned, you should be able to do `s.theme["palette"] = ColorSchemes(5).mps`. But I can implement a test for that.

**Comment by Tianbe** [comment]
![mps5](https://user-images.githubusercontent.com/42202773/172818085-88da791a-8997-4f74-9a87-3d84d13a2c9f.png)

**Comment by Tianbe** [comment]
TUM
![tum](https://user-images.githubusercontent.com/42202773/172818548-d7464827-a231-4450-b0be-ae2bf3289364.png)

**Comment by lheckmann** [comment]
Nice, they look good!

Two things:
1. To be able to import them you need to edit the __init__.py file in the plot folder and add a from `.color_schemes import *`
2. It's a not too convenient to have to define the number of colors in this step `s.theme["palette"] = ColorSchemes(5).mps` . Could you figure out a way to do a `s.theme["palette"] = ColorSchemes.mps` as it is done when using  `s.theme["palette"] = "Reds"`

**Comment by Tianbe** [comment]
I will take care of the first point
...regarding the second point, it is possible to call `ColorSchemes().mps` which is equivalent to call `ColorSchemes(5).mps` as five is the default number of colors. I could implement it such that you can do `s.theme["palette"] = ColorSchemes.mps`, but then the number of colours would not be flexible any more. However one can also do:
`cs = ColorSchemes(5)
s.theme["palette"] = cs.mps`

**Comment by lheckmann** [comment]
Thanks!

And what about doing something like this for all:

`cmap = LinearSegmentedColormap.from_list('MPS', ColorSchemes(10).mps.as_hex())
plt.colormaps.register(name='MPS', cmap=cmap)
`
Then one can just call
`s.theme["palette"] = "MPS"`

**Comment by lheckmann** [comment]
And Anna (from Helmholtz) asked if the Helmholtz colors could transition into the green in their logo, should be hex #8fb827

**Comment by Tianbe** [comment]
> And Anna (from Helmholtz) asked if the Helmholtz colors could transition into the green in their logo, should be hex #8fb827

sure, so from dark blue to green?

**Comment by Tianbe** [comment]
> Thanks!
> 
> And what about doing something like this for all:
> 
> `cmap = LinearSegmentedColormap.from_list('MPS', ColorSchemes(10).mps.as_hex())` `plt.colormaps.register(name='MPS', cmap=cmap)`
> 
> Then one can just call `s.theme["palette"] = "MPS"`

I guess that would be also possible. The reason, why I liked to use the different color palettes as attributes like `cs.mps` is that the auto-fill function in most python editors will already suggest you the different attributes and you would not have to look up the names in a documentation. This also prevents typos. What do you think?

**Comment by Tianbe** [comment]
> And Anna (from Helmholtz) asked if the Helmholtz colors could transition into the green in their logo, should be hex #8fb827
![helmholtz3](https://user-images.githubusercontent.com/42202773/178231586-a36c647e-0490-4f2b-a7b1-7279daf07665.png)

**Comment by lheckmann** [comment]
Sorry for the late response, too many things going on.

Looks really nice! :) 

And for the cmap question:

the only problem is that we are setting the color scheme via the function `s.theme["palette"] = "name_palette"` and not in the plotting function itself. That's how the framework was designed. So that's why we kind of need a way to include it this way - maybe we can give both?

**Comment by lheckmann** [comment]
Here the organization names: https://github.com/N2-Survey/SurveyFramework/pull/130#issuecomment-1181390591
