### ISSUE TITLE
Filter out No answer

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#125]
nan values are usually converted to "No Answer" or in Mental Health "No Answer" are also included, but all not included in the questions structure, therefore we cannot filter.

Can we include a filter to exclude all responses with "No Answer" to a certain question?

**Comment by fudw** [comment]
Just ran a quick check, currently this can already be accomplished by using the existing filtering method like
```python
survey[survey.responses["trait_anxiety_class"].notna()]
```
which will return a filtered survey object without any of the "No Answer" entries. Would you prefer I add this to the wiki as an example, or add such functionality to the `survey.query()` method? Which way is more used in practice?

**Comment by lheckmann** [comment]
Sorry for the late answer, I think the query method would be good, just to have it as an easy syntax.
