### ISSUE TITLE
Multiple choice plots

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#17]
Produce plots for multiple choice answers

![C5_PhD_reason](https://user-images.githubusercontent.com/74262873/136377845-edd22fcc-9821-4429-b8d3-dfed3bd7cd18.png)

Make a function that produces bar plots for multiple choice questions

What should be adjustable:

- [x] Color Scheme (with a default value that can be set in a header file)
- [x] Displaying or hiding the question title
- [x] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [x] Option for adding spaces between certain bars 
- [ ] Displaying the "No Answers" or hiding them
- [x] Threshold for percentage to be printed out
- [x] Wrapping option for text labels in case they get too long

**Comment by fudw** [comment]
I'm not 100% sure what "No Answers" is referring to here. As far as I can see, all questions of this type in the 2021 survey has no such option. Unless you meant "I don't know" or "I don't want to answer"?
