### ISSUE TITLE
Collect a mapping `<question type>: <default plot type>`

### ISSUE THREAD

**Issue by rguliev** [N2-Survey/SurveyFramework#35]

**Comment by lheckmann** [comment]
Question Type                                               Plot Type single                                    

Simple single choice                                     Basic bar plot (Issue #9)
Multiple choice                                              Multiple choice plots (Issue #17)
Array                                                             Likert Scale Plots (Issue #11)

**Comment by lheckmann** [comment]
Question Type ------------------------------------------> Type comparison plot

--------------------------------------with-------------------Simple single choice-----------------------------------Multiple Choice or array
Simple single choice ---------------------------------- Issue #10 ------------------------------------------------Issue #18

--------------------------------------with------------------Simple single choice-----------------------------------Multiple Choice or array
Multiple choice -----------------------------------------Issue #18--------------------------------------------------Issue #18
Array ----------------------------------------------------- Issue #18--------------------------------------------------Issue #18

For comparison with array plots it depends on the array how to treat the data. E.g. having a question with rating the satisfaction of different subquestions with "Very satisfied" "Satisfied" "Neither/nor" "Very dissatisfied" "Dissatisfied", where one should find how many answers are on the "positive" side ("Very satisfied" "Satisfied" + maybe half of "Neither/nor" ) and how many on the negative one. Then depending on what is wished for, the positive or negative counts/percentage are displayed in the comparison.

**Comment by lheckmann** [comment]
Additional figures (will be updated in the coming months):

Issue #19: To be shown upon request for certain questions, e.g. Income (Question B3)

**Comment by rguliev** [comment]
@lheckmann Thank you! 

This is a bit hard to read.
![image](https://user-images.githubusercontent.com/9852534/139833695-42f65a6f-e8fb-4763-a5fa-f3bee2ebe392.png)

Just for better readability. Could you please just put one table in the issue description? Here is an example of [how you can make a table](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables#creating-a-table).

**Comment by lheckmann** [comment]
Done, thank you for the instructions!
