### ISSUE TITLE
Add a method for getting responses counts

### ISSUE THREAD

**Issue by rguliev** [N2-Survey/SurveyFramework#45]
Add a method to the `LimeSurvey` class that will return counts for a provided question.
* For a single-choice question (and no-choice question like `date`, `age`, etc.), returns simple value counts. For example, for "A1" in 2021 dummy survey returns
```python
A1     18
A2      8
A3      6
NaN     4
```

* For an array question,  returns counts each value for each subquestion. For example, for "B6" in 2021 dummy survey returns data frame
```python
     B6_SQ001  B6_SQ002  B6_SQ003
NaN         6         6         6
A1         14        17         8
A2          8         3         9
A3          8        10        12
A4          6         6         1
```

* For a multi-choice question, returns counts for each choice. For example, for "B1" in 2021 dummy survey returns
```python
B1_SQ001    20
B1_SQ002     5
B1_SQ003     4
B1_SQ004     3
B1_SQ005     2
B1_SQ006     1
B1_SQ007     1
B1_SQ008     2
B1T          1
```

**NOTE:**
* It should be possible to return labels instead of Lime codes
* It should be possible to add totals (just add one more row (+ column for arrays) with totals)
* It should be possible to keep or remove `null` values

**Comment by rguliev** [comment]
My code for the examples I provided:

```python
# Inialization
from n2survey.lime import LimeSurvey
s = LimeSurvey("./data/survey_structure_2021.xml")
s.read_responses("./data/dummy_data_2021_codeonly.csv")

# A1
a1 =s.responses.loc[:,"A1"]
a1.value_counts(dropna=False)

# B1
tmp = s.questions.index[s.questions.question_group == "B1"]
b1 = s.responses.loc[:, list(tmp)]
b1.apply(lambda x: x.notnull().sum(), axis=0)

# B6
tmp = s.questions.index[s.questions.question_group == "B6"]
b6 = s.responses.loc[:, list(tmp)]
b6.apply(lambda x: x.value_counts(dropna=False), axis=0)
```

**Comment by fudw** [comment]
It could also be useful to calculate percentage here I think.
