### ISSUE TITLE
Improve transition of **kwargs between LimeServey.plot and the plot function

### ISSUE THREAD

**Issue by rguliev** [N2-Survey/SurveyFramework#54]
## Current problems we try to address:

The current transition of **kwargs is like: 

```python
class LimeSurvey:
    # ...
    def plot(..., **kwargs):
        # ...
        theme = self.theme.copy()
        theme.update(kwargs)
        ...
        the_plot_function(..., theme=theme)


def the_plot_function(..., theme):
    seaborn.set_theme(theme)
```

I.e. there is no way to "send" some arguments to the plot function itself because all values of `**kwargs` go to `theme`. 

## Possible solutions:

A possible solutions would be 

a) to split **kwargs to `theme` and `non-theme` kwargs, i.e. like:

```python
class LimeSurvey:
    # ...
    def plot(..., **kwargs):
        # ...
        # Take only theme parameters    
        theme = self.theme.copy()
        # "kwargs.pop" all parameters that are in a `all_theme_parameters` list 
        # (see https://seaborn.pydata.org/generated/seaborn.set_theme.html for the list)
        # and add them to the `theme` variable
        
        #...
        # After kwargs.pop, only "non-theme" parameters remain in the kwargs dict
        # and we send them to the plot function
        the_plot_function(..., theme=theme, **kwargs)


def the_plot_function(..., theme, **kwargs):
    seaborn.set_theme(theme)
    seaborn.someplot(..., **kwargs)
```

b) merge `self.theme` values to `kwargs` and send it all together to the plot function

```python
class LimeSurvey:
    # ...
    def plot(..., **kwargs):
        # ...
        # Merge `self.theme` dict with `kwargs` dict. kwargs should overwrite `self.theme`
        new_kwargs = self.theme.copy()
        new_kwargs.update(kwargs)
        
        #...
        # Now, we do not send `theme` parameter. The plot function itself will split them into
        # `theme` and `non-theme`
        the_plot_function(..., **new_kwargs)


def the_plot_function(..., **kwargs):
    # Take (i.e. pop) `teme` values from `kwargs`
    seaborn.set_theme(theme)
    # After `pop` only non-theme parameters are supposed to remain in the `kwargs`
    seaborn.someplot(..., **kwargs)
```

**Comment by rguliev** [comment]
The second option looks more flexible, so I would try to use it that way.

**Comment by rguliev** [comment]
@Tianbe , taking into account your changes of the `plot` function, could you please check if it makes sense? If so, would you take this issue?

**Comment by Tianbe** [comment]
I

> @Tianbe , taking into account your changes of the `plot` function, could you please check if it makes sense? If so, would you take this issue?

I can have a look. I will get in touch with you, if there is something unclear

**Comment by Tianbe** [comment]
Is it already clear what **kwargs we would have / are valid? In the version of the plot function (https://github.com/N2-Survey/SurveyFramework/blob/37_complete_plot_function/n2survey/lime/survey.py) I also checked if the given keyword is valid

**Comment by Tianbe** [comment]
Or are we always using barplots?

**Comment by Tianbe** [comment]
@rguliev  I have an issue with poetry. I realized that I have to execute `poetry install` to install the required packages, that I was missing (I guess that could be mentioned in the contributing workflow). Unfortunately I get an error message:
```
EnvCommandError

  Command C:\Users\tbeck\AppData\Local\Continuum\anaconda3\envs\n2survey\Scripts\pip.exe install --no-deps -U C:\Users\tbeck\AppData\Local
\pypoetry\Cache\artifacts\ec\6b\05\494ef9f78f818b7bc9c9803456842398cbfc2380bbba02e47f77766b15\cffi-1.15.0-cp39-cp39-win_amd64.whl errored
with the following return code 1, and output:
  WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
  WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
  Processing c:\users\tbeck\appdata\local\pypoetry\cache\artifacts\ec\6b\05\494ef9f78f818b7bc9c9803456842398cbfc2380bbba02e47f77766b15\cff
i-1.15.0-cp39-cp39-win_amd64.whl
  Installing collected packages: cffi
    Attempting uninstall: cffi
      WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
      Found existing installation: cffi 1.14.6
      Uninstalling cffi-1.14.6:
        Successfully uninstalled cffi-1.14.6
  ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\tbeck\\AppData\\Local\\Temp\\pip-uninsta
ll-gr_hcaav\\_cffi_backend.cp39-win_amd64.pyd'
  Consider using the `--user` option or check the permissions.

  WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
  WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
  WARNING: Ignoring invalid distribution -yrsistent (c:\users\tbeck\appdata\local\continuum\anaconda3\envs\n2survey\lib\site-packages)
```

but I checked the file and the path and I have the permission to access this file...

**Comment by rguliev** [comment]
Hm... I guess I will need more information:
* Do use conda?
* Where exactly do you call `poetry install`?
*

**Comment by Tianbe** [comment]
> Hm... I guess I will need more information:
> 
>     * Do use conda?
> 
>     * Where exactly do you call `poetry install`?

As far as I remember I installed poetry in a conda virtual environment. I guess could also just delete this virtual environment and set up a new one. What would be your recommendation for virtual environments? venv?

**Comment by rguliev** [comment]
Unfortunately, I do not know what is better for windows. In a linux system, poetry+pyenv handles the environment issue.
On my windows machine, I use conda virtual environment + poetry and it worked so far.
I guess dropping and re-creation of virtual environment is a good thing to try

**Comment by Tianbe** [comment]
@rguliev  I am at the moment not sure what keywords that are not related to the theme could be send to the plotfunctions. As there is anyway not an implementation the in plotfunctions to deal with these keywords, I would now raise an error, if such a keyword would be given to the plotfunction. Or did you had a different idea, when you created this issue?

**Comment by rguliev** [comment]
@Tianbe that is exactly how I expected it to be. We can add validation for non-theme keyword arguments later when plot functions themself will be more stable

**Comment by Tianbe** [comment]
@rguliev I have one more question: I would now set the arguments that you put in the current implementation of the function calls of 'single_choice_bar_plot' ('title=counts_df.columns[0]') and 'multiple_choice_bar_plot' ('display_title=True, sort="descending", bar_spacing=1.2,') as default values in the the plot functions, or should I leave this like it is.
