### ISSUE TITLE
Include Mental Health Transformations

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#75]
Convert the Mental Health Questions D1-D3 into scores and then anxiety and depression classifications and add them as new columns to the dataframe.

The code from the previous years will be shared with the one taking up the issue.

**Comment by rguliev** [comment]
Hi, 

@lheckmann could you please give an example of how it is usually used? Or how it is planned to be used?
Should this data be exported as well? If so, do we need all scores or only final ones based on all subquestions?

**Comment by lheckmann** [comment]
Hi,
it's either used by using the total score per question or the classification applied. So only final score and classifications are important and should also be exported.

Usage e.g.:

[A7_Depression.pdf](https://github.com/N2-Survey/SurveyFramework/files/7948406/A7_Depression.pdf)
![D3_supervision_colorMP](https://user-images.githubusercontent.com/74262873/151311565-513d184a-629e-46c2-a28a-62107c01af5b.png)

**Comment by rguliev** [comment]
```python
survey.add_question(**kwargs, responses=...)

class Survey:
	def __init__():
		# ...

		# Add all additional questions
		self.add_question(
			code="mh_score",
			label="Mental health score",
			type="integer",
		)
		self.add_question(
			code="mh_class",
			label="Mental health group",
			type="single-choice",
			choices={...},
		)

	def read_responses(
		self,
		**kwargs,
		transromation_questions = {"mh": "D1", "saray": "B5"}
	):
		# ...

		if transromation_questions.get("mh") is not None:
			mh_score, mh_class = calculate_metal_health_score(self.get_question(mhs_question))
			self.add_responses(code="mh_score", responses=mh_score)
			self.add_responses(code="mh_class", responses=mh_class)

	def add_question(self, **kwargs):
		# add a row to self.questions
		if responses is not None:
			self.add_responses()
		pass
   
   def add_responses(self, question, responses):
   		pass


# helpers.py
def calculate_metal_health_score():
	pass




# For combined responses
combined_survey = LimeSurvey("<path to ref XML structure file>")
combined_survey.read_responses("path to combined CSV")
```
