### ISSUE TITLE
Comparison plots - Multiple vs. Multiple Choice question

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#76]
Produce plots for comparison for more complicated question type:

E.g. multiple choice questions compared to a single choice question
![B9 SQ001 _feelfree_holidays_hue](https://user-images.githubusercontent.com/74262873/136378662-54432b8a-132e-4b2e-8beb-e1199eebb8c0.png)

- [x] Make a function that produces a comparison plots similar to the one above for multiple choice to multiple choice questions
Or think of other more reasonable ways to display the data

What should be adjustable:

- [x] Color Scheme (with a default value that can be set in a header file)
- [x] Displaying or hiding the question title
- [x] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [x] Option for adding spaces between certain bars 
- [x] Displaying the "No Answers" or hiding them
- [x] Threshold for percentage to be printed out
- [x] Wrapping option for text labels in case they get too long

**Comment by TheFlike** [comment]
This would be a plot for multiple-choice-multiple-choice question comparison
![multi_multi](https://user-images.githubusercontent.com/60603101/165049682-144bb59f-12c2-4868-9616-9721da62135b.png)
:

I think an additional bubble plot function (x-axis: answers to `question`, y-axis: answers to `compare_with` and bubbles at size of percentage around the crossing points)  would look better... maybe just for multiple-multiple-comparison and multiple-simple comparison.

**Comment by lheckmann** [comment]
Looks very nice! 

But yes, your ideas sounds also good. Since you already have the bar plot implementation, maybe we can offer both with a choosing option?

**Comment by TheFlike** [comment]
Finished the bubbleplot, works now for Multiple-Multiple-choice:
```
s.plot(
    "B1",
    compare_with="C3",
    save='multi_multi.png',
    totalbar=True,
    threshold_percentage=0,
    suppress_answers = ['Contract (internal from Helmholz)'],
    legend_columns=2,
    legend_title = True,
    plot_title=True,
    bubbles = 75,
)
```
-->
![multi_multi](https://user-images.githubusercontent.com/60603101/166155035-75143b39-a802-4b6a-a4bb-d170266655a1.png)

```
s.plot(
    "F6",
    compare_with="B1",
    save='multi_multi_2.png',
    totalbar=True,
    threshold_percentage=0,
    legend_columns=2,
    legend_title = True,
    plot_title=True,
    bubbles = 50,
    maximum_length_x_axis_answers=40
)
```
results in
![multi_multi_2](https://user-images.githubusercontent.com/60603101/166155044-57d408ea-da3e-4369-9305-21c965e77f11.png)
 
and multi-single-choice comparison works as well with bubbles:
```
s.plot(
    "C3",
    compare_with="A1",
    save='multi_single.png',
    totalbar=True,
    threshold_percentage=0,
    bar_positions=[-2.2,-1],
    suppress_answers = ['Contract (internal from Helmholz)'],
    legend_columns=2,
    plot_title="Putting in my own title",
    legend_title = True,
    bubbles = 1000,
)
```
leads to


![multi_single](https://user-images.githubusercontent.com/60603101/166155092-e82a94a9-6902-4dfc-9b3d-e3aed9b7650f.png)

**Comment by lheckmann** [comment]
How are the percentage for the bubble plots calulcated? 

It seems e.g. like the bar plot for "How is your doctoral research currently financed" and the "I have personal reasons" shows different percentage as the bubble plot in your examples here? Or is that what you fixed now?

**Comment by lheckmann** [comment]
I think what would be good for both bar and bubble plots (probably also the earlier comp plots):

Can we have the option (also as default) to display the counts per legend entry? so the reader of the figure can convert the percentage to counts immediately?

**Comment by TheFlike** [comment]
The number next to the bubbles indicates bubblesize. Thought about calculating it, but to much effort, user can choose.
Yes, I can add the total count, but I'd make it a separate issue, since it is for all comparison plots. I can add it when I finished the other ones.

**Comment by lheckmann** [comment]
Looks very nice then! I tried some of the features and it works well :) 

Can you add a description to the wiki?

**Comment by TheFlike** [comment]
will do
