### ISSUE TITLE
Basic bar plot

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#9]
Produce basic bar plots:
![B8b_holidays_taken](https://user-images.githubusercontent.com/74262873/136375949-7f319994-92fb-40b0-8a79-ddcef7db085c.png)

Make a function that produces the bar plot for all simple question types (single choice).

What should be adjustable:

- [x] Color Scheme (with a default value that can be set in a header file)
- [x] Displaying or hiding the question title
- [x] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [x] Displaying the "No Answers" or hiding them
- [x] Threshold for numbers to be displayed (e.g. <1% only the bar and a "<1%" is displayed not the total number of answers)

**Comment by Cheedge** [comment]
Hi @lheckmann ,
Question: 
1, I see the colors, but it seems not related to its percentage, right? 
2, what do you mean figure dimension?(I have not attend the meeting, if you explianed before, forgive em)
And here is what I make, it seems roughly similar. If you think something wrong please tell me
![bar_img](https://user-images.githubusercontent.com/61045942/136718630-5bfa266d-2a2c-41b3-b020-bc07f9d8fe81.png)

Best
Qi Zhi

**Comment by Cheedge** [comment]
> Hi @Cheedge, thank you for the nice work!
> 
> 1. Yes, colors are not related to the percentage here. They should have a default value (e.g. what you are using now - here we should agree on a common one to be used), but be able to be used as an input parameter if someone wants to change it.
> 2. Figure dimensions = how broad the figure is compared to it's width. Usually it's controlled in matplotlib with figsize=(10,5) or similar.
> 
> Some other comments:
> 
> * Try to order the bars according to the answer order in the xml file (use Li's code for it)
> * Import title from the xml structure (use Li's code for it)
> * Import answer titles from the xml structure (use Li's code for it)
> * y_label and axis ticks missing  - should be the number of answers.
> 
> A more general comment:
> 
> * We should decide on the precision to be used for displaying percentage.

Hi @lheckmann ,
ok, let's see this,

![bar_img](https://user-images.githubusercontent.com/61045942/137636562-2f53bb58-d726-440b-b31a-3966d42b2149.png)

you can change threshold, colors, size or font_size... or other params:

![bar_img3](https://user-images.githubusercontent.com/61045942/137640481-f7857bee-c00b-49a2-b938-93e33b03289e.png)


please check it,

can Color Scheme (with a default value that can be set in a header file)￼
can Displaying or hiding the question title￼
can Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
can Displaying the "No Answers" or hiding them￼
can (set threshold for numbers to be displayed (e.g. <1% only the bar and a "<1%" is displayed not the total number of answers))

can order the bars according to the answer order in the xml file (use Li's code for it)
can import title from the xml structure (use Li's code for it)
can import answer titles from the xml structure (use Li's code for it)
can y_label and axis ticks missing - should be the number of answers.
can a more general comment:

if there is no changes needed for the graphic part, I can make the code clean, then pull the request.

Best
Q.Z.
