### ISSUE TITLE
Synchronize question identifiers between organisations

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#93]
Make a dictionary to synchronize the questions identifiers since they can be different between Max Planck, Leibniz and Helmholtz (potentially we should also include TUM just to have the option).

I'll organize the xml structure file and notify in the issue here when they are uploaded.

**Comment by NiRuff** [comment]
I checked all questions in the 4 surveys and found the following inconsistencies:
| N2 Survey 2021 -   Helmholtz | N2 Survey 2021 - Leibniz PhD Network | N2 Survey 2021 - MPS | N² Survey 2021 at TUM                               |
|------------------------------|--------------------------------------|----------------------|-----------------------------------------------------|
|                              |                                      |                      |                                                     |
|                              |                                      |                      | A1 missing                                          |
|                              |                                      |                      | A2 split in A2a and A2b - both different    from A2 |
|                              |                                      |                      | A14 missing                                         |
|                              |                                      |                      | B1_SQ001 = B1                                       |
|                              |                                      |                      | B9a missing                                         |
|                              |                                      |                      | B12 missing                                         |
|                              |                                      |                      | C12 missing                                         |
|                              |                                      |                      | E10 missing                                         |
|                              |                                      |                      | H6 missing                                          |
|                              |                                      |                      | I7 missing                                          |
|                              |                                      |                      | J8 missing                                          |
|                              |                                      | F8_SQ001 = F8_SQ013  |                                                     |
|                              |                                      |                      | D7 missing                                          |
| D7a missing                  | D7a missing                          |                      | D7a missing                                         |
|                              |                                      |                      | K1 missing                                          |
|                              |                                      |                      | K12 missing                                         |


However, there is only one case, in which the same information is encoded by two different question names. Therefor, the following line of code should take care of the column renaming to fit the four dataframes:

```
# errors are ignored here, to make this method applicable to all four dataframes without problems - it should only change something in the mps dataframe
df.rename(columns={"F8_SQ013": "F8_SQ001"},  errors="ignore")
```
after applying this function, it might be a good idea to do an outer join of the four dataframes.

**Comment by lheckmann** [comment]
Nice thank! 

Could you still put it in a dict? 
Just to have a default way for future years where we might have more differences?

And Dawei already implemented the renaming inside his export function anyway that will take the dict "rename_columns" as input:

```
        # Rename columns if dict given
        if rename_columns:
            new_data = new_data.rename(columns=rename_columns)
```

**Comment by NiRuff** [comment]
Okay, but as we do not change any names except for the one I gave above, the only key value pair we need is the mentioned one.
This would make the dictionary very short:
rename_dict = {"F8_SQ013": "F8_SQ001"}

**Comment by lheckmann** [comment]
Good for illustration this way :) 
I'll close the issue then! 

Two propositions for next tasks for you maybe:

- We ask all organizations to export the data and you combine it to one file and try the comparison plots on it, I will make an issue for it later.
or
- Issue #101, designing default color schemes for all organizations.
